# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_SshWidget.ui'
#
# Created: Mon Nov 20 19:22:41 2017
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SshWidget(object):
    def setupUi(self, SshWidget):
        SshWidget.setObjectName("SshWidget")
        SshWidget.resize(534, 445)
        self.label = QtWidgets.QLabel(SshWidget)
        self.label.setGeometry(QtCore.QRect(30, 23, 61, 16))
        self.label.setObjectName("label")
        self.lineEditServerIP = QtWidgets.QLineEdit(SshWidget)
        self.lineEditServerIP.setGeometry(QtCore.QRect(90, 20, 101, 20))
        self.lineEditServerIP.setObjectName("lineEditServerIP")
        self.lineEditPassword = QtWidgets.QLineEdit(SshWidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(400, 20, 101, 20))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.label_2 = QtWidgets.QLabel(SshWidget)
        self.label_2.setGeometry(QtCore.QRect(333, 23, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(SshWidget)
        self.label_5.setGeometry(QtCore.QRect(30, 204, 54, 21))
        self.label_5.setObjectName("label_5")
        self.lineEditUser = QtWidgets.QLineEdit(SshWidget)
        self.lineEditUser.setGeometry(QtCore.QRect(236, 20, 91, 20))
        self.lineEditUser.setObjectName("lineEditUser")
        self.label_6 = QtWidgets.QLabel(SshWidget)
        self.label_6.setGeometry(QtCore.QRect(206, 23, 31, 16))
        self.label_6.setObjectName("label_6")
        self.pushButtonClear = QtWidgets.QPushButton(SshWidget)
        self.pushButtonClear.setGeometry(QtCore.QRect(430, 400, 71, 23))
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.plainTextEditOutput = QtWidgets.QPlainTextEdit(SshWidget)
        self.plainTextEditOutput.setGeometry(QtCore.QRect(30, 232, 471, 161))
        self.plainTextEditOutput.setReadOnly(False)
        self.plainTextEditOutput.setObjectName("plainTextEditOutput")
        self.tabWidget = QtWidgets.QTabWidget(SshWidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 60, 471, 131))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.label_3.setObjectName("label_3")
        self.lineEditArgs = QtWidgets.QLineEdit(self.tab)
        self.lineEditArgs.setGeometry(QtCore.QRect(270, 16, 181, 25))
        self.lineEditArgs.setObjectName("lineEditArgs")
        self.pushButtonGo = QtWidgets.QPushButton(self.tab)
        self.pushButtonGo.setGeometry(QtCore.QRect(350, 60, 101, 23))
        self.pushButtonGo.setObjectName("pushButtonGo")
        self.pushButtonEdit = QtWidgets.QPushButton(self.tab)
        self.pushButtonEdit.setGeometry(QtCore.QRect(240, 60, 101, 23))
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.pushButtonRefresh = QtWidgets.QPushButton(self.tab)
        self.pushButtonRefresh.setGeometry(QtCore.QRect(130, 60, 101, 23))
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(230, 19, 31, 16))
        self.label_4.setObjectName("label_4")
        self.comboBoxCmd = QtWidgets.QComboBox(self.tab)
        self.comboBoxCmd.setGeometry(QtCore.QRect(50, 15, 171, 22))
        self.comboBoxCmd.setObjectName("comboBoxCmd")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEditCmd = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditCmd.setGeometry(QtCore.QRect(50, 16, 401, 25))
        self.lineEditCmd.setObjectName("lineEditCmd")
        self.pushButtonGoSingle = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonGoSingle.setGeometry(QtCore.QRect(350, 60, 101, 23))
        self.pushButtonGoSingle.setObjectName("pushButtonGoSingle")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(SshWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SshWidget)

    def retranslateUi(self, SshWidget):
        _translate = QtCore.QCoreApplication.translate
        SshWidget.setWindowTitle(_translate("SshWidget", "ShuoGG SSH"))
        self.label.setText(_translate("SshWidget", "ServerIP"))
        self.label_2.setText(_translate("SshWidget", "Password"))
        self.label_5.setText(_translate("SshWidget", "Output:"))
        self.label_6.setText(_translate("SshWidget", "User"))
        self.pushButtonClear.setText(_translate("SshWidget", "Clear"))
        self.label_3.setText(_translate("SshWidget", "Cmd"))
        self.pushButtonGo.setText(_translate("SshWidget", "Go!"))
        self.pushButtonEdit.setText(_translate("SshWidget", "Edit"))
        self.pushButtonRefresh.setText(_translate("SshWidget", "Refresh"))
        self.label_4.setText(_translate("SshWidget", "Args"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SshWidget", "Select Mode"))
        self.pushButtonGoSingle.setText(_translate("SshWidget", "Go!"))
        self.label_9.setText(_translate("SshWidget", "Cmd"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SshWidget", "Input Mode"))

